sudo: required
dist: trusty

language: java

jdk:
  - oraclejdk7

env:
 - GDX_VERSION=1.9.2
 - GDX_VERSION=1.9.0
 - GDX_VERSION=1.8.0
 - GDX_VERSION=1.7.0

before_script:
 - .travis/xvfb.sh

after_success:
 - ./gradlew cobertura coveralls
 - .travis/deploy.sh
