sudo: required
dist: trusty

language: java

jdk:
  - oraclejdk7

env:
 - GDX_VERSION=1.9.6
 - GDX_VERSION=1.9.5
 - GDX_VERSION=1.9.4
 - GDX_VERSION=1.9.3

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 5 # give xvfb some time to start

after_success:
 - .travis/coverage.sh
 - .travis/deploy.sh
